import polars as pl
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.integrate import cumulative_simpson
import scipy.io
from numba import njit
from scipy.interpolate import LinearNDInterpolator as Lnd_interp
from scipy.interpolate import CubicSpline as cs

# 1. Load Data
matData = scipy.io.loadmat("../fs-data/FS-4/P30B Cell Data/Molicel_INR18650P30B_measurement.mat", squeeze_me=True, struct_as_record=False)
measurements = matData["measurement"]

delta = 0.1

lowCurrMeasurements = [m for m in measurements.fu.DCC if "-0.1" in m.name]

def func_SOC(I, t, starting_SOC):
    Q_nominal = 3.0  # Ah capacity of Molicel P30B
    integrated_ah = cumulative_simpson(y=I, x=t, initial=0) / 3600.0
    soc = starting_SOC + (integrated_ah / Q_nominal)
    return np.clip(soc, 0.0, 1.0)

lowVs = np.concatenate([sim.V for sim in lowCurrMeasurements])
lowTs = np.concatenate([sim.T_surf[0, :] for sim in lowCurrMeasurements])
lowSOC = np.concatenate([func_SOC(sim.I, sim.t, 1.0) for sim in lowCurrMeasurements])

voltage_curve = Lnd_interp(np.array([lowVs, lowTs]).T, lowSOC, rescale=True)

def SOC_lookup(V, T):
    # Proactively clip boundaries to prevent out-of-bounds NaNs in 2D interpolation
    V_clipped = np.clip(V, lowVs.min(), lowVs.max())
    T_clipped = np.clip(T, lowTs.min(), lowTs.max())
    SOC = voltage_curve(V_clipped, T_clipped)
    return np.clip(SOC, 0.0, 1.0)

def buildDF(measurement_set):
    frames = []
    for i, sim in enumerate(measurement_set):
        cubic = cs(sim.t, np.array([sim.I, sim.V, sim.T_surf[0, :], sim.T_surf[1, :]]), axis=1)
        t = np.arange(sim.t[0], sim.t[-1], delta)
        I, V, T_surf1, T_surf2 = cubic(t)
        starting_SOC = SOC_lookup(V[0], T_surf1[0])
        SOC = func_SOC(I, t, starting_SOC)
        frames.append(pl.DataFrame({
            "I": I, "V": V, "t": t, 
            "T_surf1": T_surf1, "T_surf2": T_surf2, "SOC": SOC,
            "run": np.ones(len(I)) * i
        }))
    return pl.concat(frames)

all_sims = np.concatenate([measurements.fu.DCC, measurements.fu.CHC, measurements.fu.DCP, measurements.fu.CHP])
aboveFreezingSims = [m for m in all_sims if m.T_surf[0, 0] > -2.0]
notHighPulse = [m for m in aboveFreezingSims if not ("-40.000C" in m.name or "-30.000C" in m.name)]
fullData = buildDF(notHighPulse)

# 2. Extract and Freeze OCV
def OCV_terminal_voltage(SOC, T, a0, a1, a2, a3, a4, a5, a6, K_T):
    return (a0 + a1 * SOC + a2 * SOC**2 + a3 * SOC**3 + a4 * SOC**4 + a5 * SOC**5 + a6 * SOC**6) * (1 + K_T * (T - 25.0))

ocv_args = np.array([2.33586300e+00, 8.70615991e+00, -3.26789721e+01, 7.63836093e+01, 
                     -9.98902031e+01, 6.83036001e+01, -1.90310137e+01, 5.90707089e-04])

# 3. Optimized Discrete State-Space Tracking
@njit
def func_V_h_fast(tau_H, M, I, delta):
    Vh_arr = np.zeros_like(I)
    alpha = np.exp(-delta / tau_H)
    beta = 1.0 - alpha
    current_direction = np.sign(I)
    for i in range(1, len(I)):
        Vh_arr[i] = Vh_arr[i - 1] * alpha + current_direction[i] * beta
    return M * Vh_arr

@njit
def func_V_X_fast(tauX, RX, I, delta):
    VX_arr = np.zeros_like(I)
    # Safely handles array inputs generated by dynamic temperature/current conditions
    alpha = np.exp(-delta / tauX)
    beta = RX * (1.0 - alpha)
    for i in range(1, len(I)):
        VX_arr[i] = VX_arr[i - 1] * alpha[i] + I[i] * beta[i]
    return VX_arr

def terminal_voltage(SOC, T, I, r0_d, r0_c, R1_ref, C1, R2_ref, C2, tau_H, M, E_a, k_I):
    T_kelvin = T + 273.15
    arrhenius_mult = np.exp((E_a * 1000.0) * (1.0 / T_kelvin - 1.0 / 298.15))
    
    # Vectorized evaluation using scaled vector definitions
    R0_d_base = (r0_d[0] + r0_d[1] * SOC + r0_d[2] * SOC**2) * arrhenius_mult
    R0_c_base = (r0_c[0] + r0_c[1] * SOC + r0_c[2] * SOC**2) * arrhenius_mult
    
    R1 = R1_ref * arrhenius_mult * (1.0 + k_I * np.exp(-np.abs(I)))
    R2 = R2_ref * arrhenius_mult
    
    tau1 = R1 * C1
    tau2 = R2 * C2
    
    V_h = func_V_h_fast(tau_H, M, I, delta)
    V_X1 = func_V_X_fast(tau1, R1, I, delta)
    V_X2 = func_V_X_fast(tau2, R2, I, delta)
    
    V_OCV = OCV_terminal_voltage(SOC, T, *ocv_args)
    V_R0 = np.where(I <= 0, R0_d_base * I, R0_c_base * I)
    
    return V_OCV + V_R0 + V_X1 + V_X2 + V_h

# 4. Nonlinear Multi-Variable Optimization Wrapper
def wrapper_post_OCV(X, r0_d0, r0_d1, r0_d2, r0_c0, r0_c1, r0_c2, R1_scaled, C1_scaled, R2_scaled, C2_scaled, tau_H, M_scaled, E_a_scaled, k_I):
    r0_d = np.array([r0_d0, r0_d1, r0_d2]) * 1e-3
    r0_c = np.array([r0_c0, r0_c1, r0_c2]) * 1e-3
    R1_ref    = R1_scaled * 1e-3
    C1        = C1_scaled * 1e2
    R2_ref    = R2_scaled * 1e-3
    C2        = C2_scaled * 1e4
    M         = M_scaled * 1e-2
    E_a       = E_a_scaled * 1.0 
    
    modelVoltages = np.zeros(X.shape[1])
    run_ids = X[3, :] 
    
    for id in np.unique(run_ids):
        mask = run_ids == id
        
        # Pass properly scaled R0 coefficient vectors directly
        modelVoltages[mask] = terminal_voltage(
            X[0, mask], X[1, mask], X[2, mask], 
            r0_d, r0_c,
            R1_ref, C1, R2_ref, C2, tau_H, M, E_a, k_I
        )
    
    actual_voltages = X[4, :]
    current_mae = np.mean(np.abs(modelVoltages - actual_voltages))
    print(f"Iteration MAE: {current_mae:.5f} V")
    
    return modelVoltages

# 5. Boundaries and Initial Guess Configuration
scaled_bounds = (
    [2.0,  -15.0,  0.0,  2.0,  -15.0,  0.0,  0.5,  1.0,  1.0,  0.5,  0.5,  0.01,  1.0,  0.01], 
    [30.0,   5.0, 40.0, 30.0,   5.0, 40.0, 20.0, 10.0, 30.0,  5.0, 120.0,  5.00,  5.0,  2.00]  
)

p0_scaled = [
    14.0, -5.0, 10.0,  
    16.0, -5.0, 10.0,  
    6.0,  4.0,         
    12.0, 1.5,         
    15.0, 0.8,         
    2.5,  0.2          
]

lessData = fullData.gather_every(10)

X_data = np.array((
    lessData["SOC"].to_numpy(), 
    lessData["T_surf1"].to_numpy(), 
    lessData["I"].to_numpy(), 
    lessData["run"].to_numpy(), 
    lessData["V"].to_numpy()
))

print(f"Starting advanced non-linear optimization with {X_data.shape} points...")
optimized_scaled_args, _ = curve_fit(
    wrapper_post_OCV, 
    X_data, 
    lessData["V"].to_numpy(), 
    p0=p0_scaled, 
    bounds=scaled_bounds, 
    maxfev=3500,
    method='trf',
    x_scale='jac'
)

final_params = {
    "r0_discharge_poly": [optimized_scaled_args[0]*1e-3, optimized_scaled_args[1]*1e-3, optimized_scaled_args[2]*1e-3],
    "r0_charge_poly":    [optimized_scaled_args[3]*1e-3, optimized_scaled_args[4]*1e-3, optimized_scaled_args[5]*1e-3],
    "R1_ref":            optimized_scaled_args[6] * 1e-3,
    "C1":                optimized_scaled_args[7] * 1e2,
    "R2_ref":            optimized_scaled_args[8] * 1e-3,
    "C2":                optimized_scaled_args[9] * 1e4,
    "tau_H":             optimized_scaled_args[10],
    "M":                 optimized_scaled_args[11] * 1e-2,
    "E_a_over_Rg":       optimized_scaled_args[12] * 1000.0,
    "k_I_current_scale": optimized_scaled_args[13]
}

print("\nOptimized Multidimensional Parameters:")
for k, v in final_params.items():
    if isinstance(v, (list, tuple, np.ndarray)):
        print(f"{k}: {[f'{float(x):.6e}' for x in v]}")
    else:
        print(f"{k}: {float(v):.6e}")