#Fan&BatteryThermalModeling
# Understanding the Tractive Battrey Accumulator Model
## We have 5 segments, with each segment having six 2x10 packs/(cells according to the parquet). 120 cells per segment, 600 cells total. 
# There are 3 holes in each segment which are cooling the batteries and the cells/packs are arranged 2x3 2 in the front and 3 wide, distance of the holes is 3 times the width/length
import polars as pl
import matplotlib.pyplot as plt
import numpy as np
import argparse
from scipy.optimize import curve_fit
import sys
sys.path.append(".")
sys.path.append("..")
sys.path.append("./Data")
from Data.FSLib.IntegralsAndDerivatives import *
from Data.FSLib.AnalysisFunctions import *
parser = argparse.ArgumentParser()
parser.add_argument(
    "parquet_path",
    type=str,
    help="Path to the Parquet file"
)

args = parser.parse_args()
df = pl.read_parquet(args.parquet_path)

#df1= pl.read_parquet("fs-data/FS-3/08172025/08172025_27autox2&45C_35C_~28Cambient_100fans.parquet")
#df2= pl.read_parquet("fs-data/FS-3/08172025/08172025_28autox3&4_45C_40C_~29Cambient_0fans.parquet")
#df3= pl.read_parquet("fs-data/FS-3/08102025/08102025Endurance1_FirstHalf.parquet")
#time starts from 0

#df1 = df1.with_columns(simpleTimeCol(df1))[6788:]
#df2 = df2.with_columns(simpleTimeCol(df2))[69330+370+6788:]
#df3 = df3.with_columns(simpleTimeCol(df3))[69330+370+6788:]
ambientTemp = 28
df = df.with_columns(simpleTimeCol(df))[6788:]
df = df.with_columns((pl.col("Time") - df["Time"][ambientTemp]).alias("Time"))

#time starts from 0
#df1 = df1.with_columns((pl.col("Time") - df1["Time"][0]).alias("Time"))
#df2 = df2.with_columns((pl.col("Time") - df2["Time"][0]).alias("Time"))
#df3 = df3.with_columns((pl.col("Time") - df3["Time"][0]).alias("Time"))

#constants
mc = 1026 # J/K 1.14*900=1026
Area = 0.02620083033 # m^2 A=n*l*c => n=20, l=0.0695, c=0.01884951822
Ac=0.00691908680696
sigma=5.67*(10**-8) # Stefan-Boltzmann constant
#AsACC=
e= 0.1 # Emissivity of Aluminium [TRAININGPARAMETER]
h = 50# W/m^2K (convection coefficient) [TRAININGPARAMETER] [-184.90636861]
k=0.205 #(Thermal conductivity of the cell) [calculate physically]
k1=0.205

I = df["SME_TEMP_BusCurrent"] ## Accordingly change the 'df1' to any data frame choosen] 
Temprature=(((I**2)*(16*(10**-3)))/mc) 
IntegratedTemp=in_place_integrate(Temprature, dt=60/5035) #integrating the temperature change to get the total temperature generated by the battery over time
q1=h*Area*(IntegratedTemp-ambientTemp) #Cooling
q1=q1/mc 
q2=-k*IntegratedTemp*Ac #Pack to Pack conduction; k: Thermal conductivity, Ac: Cross-section area of the Pack [TRAININGPARAMETER]
q2=q2/mc
q3=k1*surfaceTemp*Ac2 #Cell to enclosure conduction; k1: Thermal conductivity, Ac2: Cross-section area of the Accumulator wall [TRAININGPARAMETER]
#q4=h*AsACC*(ACCst-ambientTemp) #enclosure to air convection; AsACC: Surface area of the accumulator [TRAININGPARAMETER]
#q5=e*sigma*AsACC*(ACCst^4-ambientTemp^4) #Radiation; e: emissivity of aluminium, sigma: Stefan-Boltzmann constant [TRAININGPARAMETER]
IntegratedTemp=in_place_integrate(Temprature, dt=60/5035) #integrating the temperature change to get the total temperature generated by the battery over time
# dT/dt = (I^2*R - h*A*(T-T_ambient)) / (m*c))
temp_cols = [f"ACC_SEG{s}_TEMPS_CELL{c}" for s in range(5) for c in range(6)] #We are not using this anymore since out Ts is now measured by T/mc instead 
#Q=(q2+q3)-(q1+q5+q4)

temps = np.array((30, 19))

for i in range(len(Temprature)):
    


df = df.with_columns(
df.select([pl.col(col).cast(pl.Float32) for col in temp_cols])
.mean_horizontal()
.alias("TempMean")
)

#plt.ylim(bottom=ambientTemp)
plt.plot(df["Time"], IntegratedTemp)
plt.xlabel("Time (s)")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.show()  

#python Data/BatteryThermalModel/FanBatteryThermalModeling.py fs-data/FS-3/08102025/08102025Endurance1_FirstHalf.parquet
#python Data/BatteryThermalModel/FanBatteryThermalModeling.py fs-data/FS-3/08172025/08172025_27autox2&45C_35C_~28Cambient_100fans.parquet
#python Data/BatteryThermalModel/FanBatteryThermalModeling.py fs-data/FS-3/08102025/08102025Endurance1_SecondHalf.parquet
#python Data/BatteryThermalModel/FanBatteryThermalModeling.py fs-data/FS-3/08102025/08102025RollingResistanceTestP1.parquet